# Generated by Django 5.0.4 on 2024-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('fname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=11, unique=True)),
                ('cnic', models.CharField(max_length=14, unique=True)),
                ('fcnic', models.CharField(max_length=14, unique=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('qulification', models.CharField(max_length=100)),
                ('laptop', models.CharField(max_length=100)),
            ],
        ),
    ]
