# Generated by Django 5.0.4 on 2024-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='students',
            name='cnic',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='fcnic',
            field=models.CharField(max_length=14),
        ),
    ]
