# Generated by Django 5.0.4 on 2024-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0002_alter_students_phone_alter_students_cnic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=200)),
            ],
        ),
    ]
